"""
Django settings for barbsite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import tempfile
from pathlib import Path

# Load environment variables from a project root .env file when available.
try:
    from dotenv import load_dotenv
    _env_path = Path(__file__).resolve().parent.parent / '.env'
    load_dotenv(_env_path)
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-_jpj!)mwn&0n-#rk@4ty81vn1eweb6&uxomn+9d7j=6-(w3gnz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allow all vercel.app domains and localhost
_default_hosts = ['localhost', '127.0.0.1', 'julies-twinkle.vercel.app', 'julies-twinkle-bsl6j0pah-maltildanyabokes-projects.vercel.app', '*.vercel.app']
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', ','.join(_default_hosts)).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barbsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'booking' / 'templates',
            os.path.join(BASE_DIR, 'booking', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barbsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# In local development we use BASE_DIR/db.sqlite3.
# On Vercel / other serverless hosts, use /tmp/db.sqlite3 because the app directory is not writable.
DEFAULT_SQLITE_PATH = BASE_DIR / 'db.sqlite3'
VERCEL_SQLITE_PATH = Path('/tmp/db.sqlite3')


def _dir_writable(path: Path) -> bool:
    try:
        path.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryFile(dir=str(path)):
            pass
        return True
    except OSError:
        return False


def _resolve_database_path() -> Path:
    sqlite_path = os.environ.get('SQLITE_PATH')
    if sqlite_path:
        return Path(sqlite_path)

    if os.environ.get('VERCEL') or os.environ.get('VERCEL_ENV') or os.environ.get('VERCEL_URL'):
        return VERCEL_SQLITE_PATH

    if not _dir_writable(DEFAULT_SQLITE_PATH.parent):
        return VERCEL_SQLITE_PATH

    if DEFAULT_SQLITE_PATH.exists() and not os.access(DEFAULT_SQLITE_PATH, os.W_OK):
        return VERCEL_SQLITE_PATH

    return DEFAULT_SQLITE_PATH


database_path = _resolve_database_path()
try:
    database_path.parent.mkdir(parents=True, exist_ok=True)
    database_path.touch(exist_ok=True)
except OSError:
    database_path = VERCEL_SQLITE_PATH

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(database_path),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Set static root for production/Vercel
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Barb Barbershop <matildahnyaboke@gmail.com>')
SHOP_BOOKING_EMAIL = os.environ.get('SHOP_BOOKING_EMAIL', 'matildahnyaboke@gmail.com')

if EMAIL_BACKEND.startswith('anymail.backends'):
    try:
        import anymail  # noqa: F401
        INSTALLED_APPS += ['anymail']
        ANYMAIL = {
            'MAILJET_API_KEY': os.environ.get('MAILJET_API_KEY'),
            'MAILJET_SECRET_KEY': os.environ.get('MAILJET_SECRET_KEY'),
        }
    except ImportError:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        # anymail not installed, so fallback to console backend

